# -*- coding: utf-8 -*-
"""LicensePlate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CfKqD8aOrA-3RNe9D2g1BHwD8A6zHWQM
"""

!pip install easyocr

from google.colab.patches import cv2_imshow
import cv2
import imutils
import easyocr
import warnings

warnings.filterwarnings("ignore", category=UserWarning, module="easyocr")

image = cv2.imread('/content/image4.jpg')
if image is None:
    print("Failed to load image")
    exit(1)

image = imutils.resize(image,width=500)
cv2_imshow(image)
cv2.waitKey(0)

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
smooth = cv2.bilateralFilter(gray, 11, 17, 17)
cv2_imshow(gray)
cv2.waitKey(0)

corner = cv2.Canny(gray, 170, 200)
cv2_imshow(corner)
cv2.waitKey(0)

contours, _ = cv2.findContours(corner.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

image1 = image.copy()
cv2.drawContours(image1, contours, -1, (0, 0, 255), 3)
cv2_imshow(image1)
cv2.waitKey(0)

contours = sorted(contours, key=cv2.contourArea, reverse=True)[:30]
number_plate = None
image2 = image.copy()
cv2.drawContours(image2, contours, -1, (0, 255, 0), 3)
cv2_imshow(image2)
cv2.waitKey(0)

count = 0
name = 1

for contour in contours:
    perimeter = cv2.arcLength(contour, True)
    approx = cv2.approxPolyDP(contour, 0.02 * perimeter, True)
    if len(approx) == 4:
        number_plate = approx
        x, y, w, h = cv2.boundingRect(contour)
        crp_image = image[y:y + h, x:x + w]
        cv2.imwrite(str(name) + '.png', crp_image)
        name += 1
        break

cv2.drawContours(image, [number_plate], -1, (0, 255, 0), 3)
cv2_imshow(image)
cv2.waitKey(0)

crp_img = '1.png'
cv2_imshow(cv2.imread(crp_img))
cv2.waitKey(0)


cropped_image = cv2.imread(crp_img)
crpresize = imutils.resize(cropped_image, width=600)
cv2_imshow(crpresize)
cv2.waitKey(0)


# text = pytesseract.image_to_string(crpresize, config='--psm 6', lang='eng')
# print("Text extracted from the image:")
# print(text)



reader = easyocr.Reader(['en'])
result = reader.readtext('1.png', detail=0)
print(result[0])